name: Continuous Integration

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build-and-test:
    name: Build and Unit Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            cmake g++ make git \
            libasound2-dev \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libxcursor-dev \
            libxinerama-dev

      - name: Install Raylib
        run: |
          git clone https://github.com/raysan5/raylib.git
          cd raylib
          mkdir build
          cd build
          cmake .. -DBUILD_SHARED_LIBS=ON
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: .
          build-dir: build

      - name: Run Unit Tests
        run: ctest --test-dir build --output-on-failure

      - name: Notify Discord
        if: success() && github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"content\": \"✅ PR mergeada com sucesso na branch **${{ github.event.pull_request.base.ref }}**!\n\n📦 Repositório: ${{ github.repository }}\n🔀 PR: #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}\n👤 Autor: ${{ github.event.pull_request.user.login }}\n🔗 Link: ${{ github.event.pull_request.html_url }}\"
          }" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
