name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write   # se quiser que thread-comments funcionem em PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run C/C++ linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'         # usar .clang-format
          tidy-checks: ''       # usar .clang-tidy
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}

      - name: Fail fast if lint fails
        if: steps.linter.outputs.checks-failed != '0'
        run: exit 1
